#!/usr/bin/env bash
# Norinth one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/revenant-research/norinth/main/scripts/install.sh | bash
#
# What it does, in order:
#   1. Checks for Docker (offers to install it on Ubuntu/Debian), curl, openssl.
#   2. Creates ./norinth (or $NORINTH_DIR) and fetches docker-compose.yml.
#   3. Generates every secret into .env: PostgreSQL password, NORINTH_SECRET_KEY,
#      a random administrator password. The platform therefore never boots with
#      development defaults.
#   4. Pulls the signed image from GHCR (or builds from source with --source).
#   5. Starts PostgreSQL and Norinth, waits for /health, prints the URL and the
#      administrator login. The first visit opens the setup wizard.
#
# Flags:  --dir PATH   --port N   --source   --no-pull   --upgrade   --uninstall   --yes
# Re-running is safe: an existing .env is never overwritten.
set -euo pipefail

REPO_RAW="${NORINTH_REPO_RAW:-https://raw.githubusercontent.com/revenant-research/norinth/main}"
IMAGE="${NORINTH_IMAGE:-ghcr.io/revenant-research/norinth:latest}"
DIR="${NORINTH_DIR:-$PWD/norinth}"
PORT="${NORINTH_PORT:-8001}"
MODE="install"
FROM_SOURCE=0
NO_PULL=0
ASSUME_YES=0

say()  { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --source) FROM_SOURCE=1; shift ;;
    --no-pull) NO_PULL=1; shift ;;
    --upgrade) MODE="upgrade"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) die "unknown flag: $1" ;;
  esac
done

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required. $2"; }

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    docker info >/dev/null 2>&1 || die "Docker is installed but the daemon is not running (or you lack permission). Start Docker and re-run."
    return
  fi
  if [ -f /etc/os-release ] && grep -qiE 'ubuntu|debian' /etc/os-release; then
    say "Docker is not installed."
    if [ "$ASSUME_YES" = 1 ] || { [ -t 0 ] && read -r -p "  Install Docker Engine with Docker's official script? [y/N] " a && [ "${a:-n}" = y ]; }; then
      curl -fsSL https://get.docker.com | sh
      command -v docker >/dev/null 2>&1 || die "Docker installation failed."
      return
    fi
  fi
  die "Docker with the compose plugin is required. Install it from https://docs.docker.com/get-docker/ and re-run."
}

compose() { (cd "$DIR" && docker compose "$@"); }

random_secret() { openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-40; }

write_env() {
  if [ -f "$DIR/.env" ]; then
    info "Keeping existing $DIR/.env (secrets are never regenerated)."
    return
  fi
  local pg_pw admin_pw secret_key
  pg_pw="$(random_secret)"; admin_pw="$(random_secret | cut -c1-20)"; secret_key="$(openssl rand -base64 32 | tr -d '\n')"
  umask 077
  cat > "$DIR/.env" <<ENV
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
NORINTH_IMAGE=${IMAGE}
NORINTH_PORT=${PORT}
POSTGRES_PASSWORD=${pg_pw}
NORINTH_SECRET_KEY=${secret_key}
NORINTH_SUPER_ADMIN_EMAIL=admin@norinth.local
NORINTH_SUPER_ADMIN_PASSWORD=${admin_pw}
# Set to your public URL (https://norinth.example.com) when behind TLS/ingress,
# then set NORINTH_COOKIE_SECURE=1 and NORINTH_TRUST_PROXY=1.
NORINTH_PUBLIC_BASE_URL=http://localhost:${PORT}
NORINTH_COOKIE_SECURE=0
NORINTH_TRUST_PROXY=0
ENV
  info "Wrote $DIR/.env with generated secrets."
}

fetch_compose() {
  if [ "$FROM_SOURCE" = 1 ]; then
    need git "Install git to build from source."
    if [ -f "$DIR/apps/platform/Dockerfile" ]; then
      info "Using the existing source checkout at $DIR."
    else
      git clone --depth 1 https://github.com/revenant-research/norinth "$DIR"
    fi
  else
    mkdir -p "$DIR"
    curl -fsSL "$REPO_RAW/docker-compose.yml" -o "$DIR/docker-compose.yml"
    mkdir -p "$DIR/scripts"
    for f in backup.sh restore.sh; do curl -fsSL "$REPO_RAW/scripts/$f" -o "$DIR/scripts/$f" && chmod +x "$DIR/scripts/$f"; done
  fi
}

wait_healthy() {
  local _attempt
  for _attempt in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  compose logs --tail 50 norinth || true
  die "Norinth did not become healthy within two minutes. Logs above."
}

case "$MODE" in
  uninstall)
    [ -d "$DIR" ] || die "Nothing to uninstall at $DIR."
    say "This stops Norinth and DELETES its database volume at $DIR."
    if [ "$ASSUME_YES" = 1 ] || { [ -t 0 ] && read -r -p "  Type 'delete' to confirm: " a && [ "$a" = delete ]; }; then
      compose down -v
      info "Containers and data removed. $DIR/.env left in place; delete it yourself."
    else
      info "Aborted."
    fi
    exit 0 ;;
  upgrade)
    [ -f "$DIR/.env" ] || die "No install found at $DIR. Run without --upgrade first."
    ensure_docker
    say "Upgrading Norinth at $DIR"
    fetch_compose
    if [ "$FROM_SOURCE" = 1 ]; then compose build; else compose pull; fi
    compose up -d
    wait_healthy
    say "Upgraded. Migrations ran on boot; check Console → Overview → Schema."
    exit 0 ;;
esac

say "Installing Norinth into $DIR"
need curl "Install curl and re-run."
need openssl "Install openssl and re-run."
ensure_docker
fetch_compose
write_env
say "Starting PostgreSQL and Norinth"
if [ "$FROM_SOURCE" = 1 ]; then compose build; elif [ "$NO_PULL" = 0 ]; then compose pull; fi
compose up -d
wait_healthy

# shellcheck disable=SC1090,SC1091
set -a; . "$DIR/.env"; set +a
say "Norinth is running."
info "URL:            http://localhost:${PORT}"
info "Administrator:  ${NORINTH_SUPER_ADMIN_EMAIL}"
info "Password:       ${NORINTH_SUPER_ADMIN_PASSWORD}   (also in $DIR/.env)"
info ""
info "Next: open the URL. The setup wizard walks you through naming your organization,"
info "creating an ingestion key, and instrumenting your first application."
info ""
info "Manage:  cd $DIR && docker compose logs -f | docker compose down | scripts/backup.sh"
info "Upgrade: curl -fsSL $REPO_RAW/scripts/install.sh | bash -s -- --upgrade --dir $DIR"
