#!/usr/bin/env bash
# Norinth one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/revenant-research/norinth/main/scripts/install.sh | bash
#
# What it does, in order:
#   1. Checks for Docker (offers to install it on Ubuntu/Debian), curl, openssl.
#   2. Creates ./norinth (or $NORINTH_DIR) and fetches docker-compose.yml.
#   3. Generates every secret into .env: PostgreSQL password, NORINTH_SECRET_KEY,
#      a random administrator password. The platform therefore never boots with
#      development defaults.
#   4. Pulls the image from GHCR and, if cosign is installed, verifies its
#      keyless signature before running it (or builds from source with --source).
#   5. Starts PostgreSQL and Norinth, waits for /health, prints the URL and the
#      administrator login. The first visit opens the setup wizard.
#
# Flags:  --dir PATH  --port N  --source  --no-pull  --no-verify  --upgrade  --uninstall  --yes
# Re-running is safe: an existing .env is never overwritten.
#
# Uninstall deletes the database volume. --yes does NOT authorize that deletion;
# a non-interactive uninstall additionally requires NORINTH_DELETE_DATA=1.
set -euo pipefail

REPO_RAW="${NORINTH_REPO_RAW:-https://raw.githubusercontent.com/revenant-research/norinth/main}"
IMAGE="${NORINTH_IMAGE:-ghcr.io/revenant-research/norinth:latest}"
# Keyless-signing identity for verification: the release workflow in this repo.
COSIGN_IDENTITY_RE="${NORINTH_COSIGN_IDENTITY_RE:-^https://github.com/revenant-research/norinth/}"
COSIGN_ISSUER="${NORINTH_COSIGN_ISSUER:-https://token.actions.githubusercontent.com}"
DIR="${NORINTH_DIR:-$PWD/norinth}"
PORT="${NORINTH_PORT:-8001}"
PORT_EXPLICIT=0
MODE="install"
FROM_SOURCE=0
NO_PULL=0
NO_VERIFY=0
ASSUME_YES=0

say()  { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --port) PORT="$2"; PORT_EXPLICIT=1; shift 2 ;;
    --source) FROM_SOURCE=1; shift ;;
    --no-pull) NO_PULL=1; shift ;;
    --no-verify) NO_VERIFY=1; shift ;;
    --upgrade) MODE="upgrade"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) die "unknown flag: $1" ;;
  esac
done

# an existing install keeps the port it was installed on. without this an
# upgrade of anything not on the default port polls 8001, times out, and reports
# a failure for an upgrade that worked
if [ "$PORT_EXPLICIT" = 0 ] && [ -f "$DIR/.env" ]; then
  existing_port=$(sed -n 's/^NORINTH_PORT=//p' "$DIR/.env" | head -1)
  [ -n "$existing_port" ] && PORT="$existing_port"
fi

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required. $2"; }

# set to "plugin" (docker compose) or "standalone" (docker-compose) by ensure_docker
COMPOSE_KIND=""

detect_compose() {
  command -v docker >/dev/null 2>&1 || return 1
  if docker compose version >/dev/null 2>&1; then
    COMPOSE_KIND="plugin"
    return 0
  fi
  # older installs, and some desktop setups, only have the standalone binary
  if command -v docker-compose >/dev/null 2>&1 && docker-compose version >/dev/null 2>&1; then
    COMPOSE_KIND="standalone"
    return 0
  fi
  return 1
}

ensure_docker() {
  if detect_compose; then
    docker info >/dev/null 2>&1 || die "Docker is installed but the daemon is not running (or you lack permission). Start Docker and re-run."
    return
  fi
  if [ -f /etc/os-release ] && grep -qiE 'ubuntu|debian' /etc/os-release; then
    say "Docker is not installed."
    if [ "$ASSUME_YES" = 1 ] || { [ -t 0 ] && read -r -p "  Install Docker Engine with Docker's official script? [y/N] " a && [ "${a:-n}" = y ]; }; then
      # Pinned commit of https://github.com/docker/docker-install, the source of
      # get.docker.com, so this always runs a script that was reviewed rather
      # than whatever the domain serves today. Bump the hash to update.
      curl -fsSL https://raw.githubusercontent.com/docker/docker-install/42dcae692436f34526524ed46d3b32885c9355f5/install.sh | sh
      detect_compose || die "Docker installation failed."
      return
    fi
  fi
  die "Docker with Compose is required (either 'docker compose' or 'docker-compose'). Install it from https://docs.docker.com/get-docker/ and re-run."
}

compose() {
  if [ "$COMPOSE_KIND" = "standalone" ]; then
    (cd "$DIR" && docker-compose "$@")
  else
    (cd "$DIR" && docker compose "$@")
  fi
}

random_secret() { openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-40; }

write_env() {
  if [ -f "$DIR/.env" ]; then
    info "Keeping existing $DIR/.env (secrets are never regenerated)."
    return
  fi
  local pg_pw admin_pw secret_key
  pg_pw="$(random_secret)"; admin_pw="$(random_secret | cut -c1-20)"; secret_key="$(openssl rand -base64 32 | tr -d '\n')"
  umask 077
  cat > "$DIR/.env" <<ENV
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
NORINTH_IMAGE=${IMAGE}
NORINTH_PORT=${PORT}
POSTGRES_PASSWORD=${pg_pw}
NORINTH_SECRET_KEY=${secret_key}
NORINTH_SUPER_ADMIN_EMAIL=admin@norinth.local
NORINTH_SUPER_ADMIN_PASSWORD=${admin_pw}
# Set to your public URL (https://norinth.example.com) when behind TLS/ingress,
# then set NORINTH_COOKIE_SECURE=1 and NORINTH_TRUST_PROXY=1.
NORINTH_PUBLIC_BASE_URL=http://localhost:${PORT}
NORINTH_COOKIE_SECURE=0
NORINTH_TRUST_PROXY=0
ENV
  info "Wrote $DIR/.env with generated secrets."
}

fetch_compose() {
  if [ "$FROM_SOURCE" = 1 ]; then
    need git "Install git to build from source."
    if [ -f "$DIR/apps/platform/Dockerfile" ]; then
      info "Using the existing source checkout at $DIR."
    else
      git clone --depth 1 https://github.com/revenant-research/norinth "$DIR"
    fi
  else
    mkdir -p "$DIR"
    curl -fsSL "$REPO_RAW/docker-compose.yml" -o "$DIR/docker-compose.yml"
    mkdir -p "$DIR/scripts"
    for f in backup.sh restore.sh; do curl -fsSL "$REPO_RAW/scripts/$f" -o "$DIR/scripts/$f" && chmod +x "$DIR/scripts/$f"; done
  fi
}

wait_healthy() {
  local _attempt
  for _attempt in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  compose logs --tail 50 norinth || true
  die "Norinth did not become healthy within two minutes. Logs above."
}

verify_image() {
  # Building from source produces no signed image to verify.
  [ "$FROM_SOURCE" = 1 ] && return 0
  if [ "$NO_VERIFY" = 1 ]; then
    info "Signature verification skipped (--no-verify)."
    return 0
  fi
  if command -v cosign >/dev/null 2>&1; then
    say "Verifying image signature with cosign"
    if cosign verify \
        --certificate-identity-regexp "$COSIGN_IDENTITY_RE" \
        --certificate-oidc-issuer "$COSIGN_ISSUER" \
        "$IMAGE" >/dev/null 2>&1; then
      info "Signature verified (keyless, GitHub Actions OIDC)."
    else
      die "cosign could not verify $IMAGE. Refusing to run an unverified image. Pin a trusted digest via NORINTH_IMAGE, or pass --no-verify to skip (not recommended)."
    fi
  else
    info "cosign not installed; skipping signature verification of $IMAGE."
    info "Install cosign (https://docs.sigstore.dev) to verify, or use --source to build locally."
  fi
}

case "$MODE" in
  uninstall)
    [ -d "$DIR" ] || die "Nothing to uninstall at $DIR."
    say "This stops Norinth and DELETES its database volume at $DIR."
    # --yes deliberately does NOT authorize data deletion; non-interactively,
    # deleting the database requires the explicit NORINTH_DELETE_DATA=1, so a
    # stray --yes in a script can never destroy a database
    confirmed=0
    if [ -t 0 ]; then
      read -r -p "  Type 'delete' to confirm: " a && [ "$a" = delete ] && confirmed=1
    elif [ "${NORINTH_DELETE_DATA:-0}" = 1 ]; then
      confirmed=1
    else
      die "Refusing to delete the database non-interactively. Re-run with NORINTH_DELETE_DATA=1 to confirm."
    fi
    if [ "$confirmed" = 1 ]; then
      compose down -v
      info "Containers and data removed. $DIR/.env left in place; delete it yourself."
    else
      info "Aborted."
    fi
    exit 0 ;;
  upgrade)
    [ -f "$DIR/.env" ] || die "No install found at $DIR. Run without --upgrade first."
    ensure_docker
    say "Upgrading Norinth at $DIR"
    fetch_compose
    if [ "$FROM_SOURCE" = 1 ]; then compose build; else compose pull; fi
    verify_image
    compose up -d
    wait_healthy
    say "Upgraded. Migrations ran on boot; check Console → Overview → Schema."
    exit 0 ;;
esac

say "Installing Norinth into $DIR"
need curl "Install curl and re-run."
need openssl "Install openssl and re-run."
ensure_docker
fetch_compose
write_env
say "Starting PostgreSQL and Norinth"
if [ "$FROM_SOURCE" = 1 ]; then compose build; elif [ "$NO_PULL" = 0 ]; then compose pull; fi
verify_image
compose up -d
wait_healthy

env_value() { sed -n "s/^$1=//p" "$DIR/.env" | head -1; }
say "Norinth is running."
info "URL:            http://localhost:${PORT}"
info "Administrator:  $(env_value NORINTH_SUPER_ADMIN_EMAIL)"
info "Password:       $(env_value NORINTH_SUPER_ADMIN_PASSWORD)   (also in $DIR/.env)"
info ""
info "Next: open the URL. The setup wizard walks you through naming your organization,"
info "creating an ingestion key, and instrumenting your first application."
info ""
compose_cmd() { [ "$COMPOSE_KIND" = "standalone" ] && printf 'docker-compose' || printf 'docker compose'; }
info "Manage:  cd $DIR && $(compose_cmd) logs -f | $(compose_cmd) down | scripts/backup.sh"
info "Upgrade: curl -fsSL $REPO_RAW/scripts/install.sh | bash -s -- --upgrade --dir $DIR"
